name: Build artifacts
run-name: Build on '${{ github.ref_name }}' branch push (${{ github.event.head_commit.message }})

on:
  push:
    branches:
      - '**'

jobs:

  validate:
    name: Check
    uses: ./.github/workflows/sub-check.yml

  docker:
    name: Build
    needs: [ validate ]
    uses: ./.github/workflows/sub-build-docker.yml
    with:
      REGISTRY_IMAGE: ${{ vars.REGISTRY_IMAGE || 'berkut174/webtlo' }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  zip:
    name: Build
    needs: [ validate ]
    uses: ./.github/workflows/sub-build-zip.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # PHP: https://windows.php.net/download Non-Thread-Safe
          PHP_RELEASES='https://windows.php.net/downloads/releases'
          
          PHP_VERSION=`curl -s '$PHP_RELEASES/releases.json' | jq  '."8.2".version'`
          PHP_PATH="php-$PHP_VERSION-nts-Win32-vs16-x64"
          
          echo $PHP_VERSION
          
          echo $PHP_PATH
          
          wget -nv -O php.zip "$PHP_RELEASES/$PHP_PATH.zip"
          unzip -d $zip_dir/php php.zip
