name: Build artifacts
run-name: Build on '${{ github.ref_name }}' branch push (${{ github.event.head_commit.message }})

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $WEBTLO_VERSION
          echo ${{ vars.WEBTLO_VERSION }}
          echo ${{ github.ref_name }}
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha,prefix=''

      - run: cat src/version.json

      - name: Test
        run: |
          echo $DOCKER_METADATA_OUTPUT_VERSION
          cd src
          token=$( cat version.json | jq --arg V -${{ github.ref_name }} '.version+=$V' | jq --arg SH $DOCKER_METADATA_OUTPUT_VERSION '.sha=$SH')
          
          echo $token
#          echo "VERSION_JSON=$token" >> "$GITHUB_ENV"
          

      - run: echo "$VERSION_JSON"

#  validate:
#    name: Check
#    uses: ./.github/workflows/sub-check.yml

#  docker:
#    name: Build
##    needs: [ validate ]
#    uses: ./.github/workflows/sub-build-docker.yml
#    with:
#      REGISTRY_IMAGE: ${{ vars.REGISTRY_IMAGE || 'berkut174/webtlo' }}
#    secrets:
#      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
#      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#  zip:
#    name: Build
##    needs: [ validate ]
#    uses: ./.github/workflows/sub-build-zip.yml