on:
  workflow_call:
    inputs:
      image-name:
        default: 'berkut174/webtlo'
        required: false
        type: string
    secrets:
      dockerhub-login:
        required: true
      dockerhub-access-token:
        required: true

jobs:
  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.image-name }}
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 'nebionik/webtlo'
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-login }}
          password: ${{ secrets.dockerhub-access-token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}