on:
  workflow_call:

jobs:
  build-nix:
    name: Build webtlo
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore composer
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: cp -r src webtlo.local
      - run: mkdir -p release
      - run: zip -r -9 "release/webtlo.zip" webtlo.local
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          path: release/webtlo.zip