name: Build release

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml

  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [ validate ]
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            berkut174/webtlo
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
  #      - name: Login to DockerHub
  #        if: github.event_name != 'pull_request'
  #        uses: docker/login-action@v2
  #        with:
  #          username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #      - name: Build and push
  #        uses: docker/build-push-action@v3
  #        with:
  #          context: .
  #          push: ${{ github.event_name != 'pull_request' }}
  #          platforms: linux/amd64,linux/arm64
  #          tags: ${{ steps.meta.outputs.tags }}
  #          labels: ${{ steps.meta.outputs.labels }}

  build:
    name: Build webtlo zip
    runs-on: ubuntu-latest
    needs: [ validate ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: 'src'
          args: "--ignore-platform-reqs --optimize-autoloader"
          dev: no

      - run: mkdir -p release
      - name: Build unix webtlo
        run: |
          zip_name=webtlo.zip

          mv src webtlo.local
          zip -r -9 "release/$zip_name" webtlo.local

          echo "Done $zip_name"

      - name: Build win webtlo
        run: |
          zip_name=webtlo-win-${{ github.ref_name }}.zip
          
          chmod +x ./win/make-wtlo-win.sh
          ./win/make-wtlo-win.sh

          mv "webtlo.local" "webtlo-win/nginx/wtlo"
          zip -r -9 "release/$zip_name" webtlo-win

          echo "Done $zip_name"
        env:
          NGINX_VERSION: ${{ vars.NGINX_VERSION }}
          PHP_VERSION: ${{ vars.PHP_VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: releases
          path: release/*.zip
          retention-days: 7

      - name: Cache release
        uses: actions/cache@v3
        with:
          path: ./release
          key: ${{ github.sha }}-release

  release:
    name: Make release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ build, docker ]
    steps:
      - name: Restore release
        id: restore-release
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}-release
          path: ./release

      - uses: softprops/action-gh-release@v1
        name: Create release
        with:
          files: release/*.zip
          draft: true
          prerelease: true
          generate_release_notes: true
