name: Build release

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/check-code-style.yml

  composer:
    name: Install dependencies
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        working_dir: 'src'
        args: "--ignore-platform-reqs --optimize-autoloader"
        dev: no
    - name: Cache composer
      uses: actions/cache@v3
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}


  build-win:
    name: Build
    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/')
    needs: [composer]
    steps:
    - uses: ./.github/workflows/build-nix.yml
    - uses: ./.github/workflows/build-win.yml
    - uses: softprops/action-gh-release@v1
      name: Create release
      with:
        files: release/*.zip
        prerelease: true
