name: Build release

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
#  validate:
#    name: Validate
#    uses: ./.github/workflows/check-code-style.yml

  composer:
    name: Install dependencies
    runs-on: ubuntu-latest
#    needs: [ validate ]
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          working_dir: 'src'
          args: "--ignore-platform-reqs --optimize-autoloader"
          dev: no
      - name: Cache composer
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./src
          key: ${{ github.sha }}

  build-nix:
    name: Build webtlo
    runs-on: ubuntu-latest
    needs: [ composer ]
#    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Restore composer
        uses: actions/cache@v3
        id: restore-build
        with:
          path: ./src
          key: ${{ github.sha }}

      - run: mkdir -p release
      - run: cp -r src webtlo.local
      - run: zip -r -9 "release/webtlo.zip" webtlo.local

      - run: ./make-wtlo-win.sh
      - run: mv "webtlo.local" "webtlo-win/nginx/wtlo"
      - run: zip -r -9 "release/webtlo-win-{{ github.ref_name }}.zip" webtlo-win

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          path: release/*.zip

#      - uses: softprops/action-gh-release@v1
#        name: Create release
#        with:
#          files: release/*.zip
#          prerelease: true
