on:
  workflow_call:

jobs:
  php-cs-fixer:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Code
        uses: super-linter/super-linter@v5

      - uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: php-cs-fixer
        uses: ale94lko/php-cs-fixer-action@v1.0.1
        with:
          php-cs-fixer-version: v3.34.1