name: ci

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'
jobs:
  php-cs-fixer:
    name: Check code style
    steps:
      - uses: actions/checkout@v2
      - name: php-cs-fixer
        uses: ale94lko/php-cs-fixer-action@v1.0.1
        with:
          php-cs-fixer-version: v3.34.1

  composer:
    name: Install composer
    needs: [php-cs-fixer]

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6
      with:
        working_dir: 'src'
        args: "--ignore-platform-reqs --optimize-autoloader"
        dev: no

  build:
    name: Build webtlo
    if: startsWith(github.ref, 'refs/tags/')
    needs: [composer]
    steps:
    - run: cp -r src webtlo.local && zip -r -9 webtlo.zip webtlo.local/

    - uses: actions/upload-artifact@v3
      name: Upload artifact
      with:
        path: webtlo.zip

    - uses: softprops/action-gh-release@v1
      name: Create release
      with:
        files: webtlo.zip
        prerelease: true
