name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'
jobs:
  php-cs-fixer:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: php-cs-fixer
        uses: ale94lko/php-cs-fixer-action@v1.0.1
        with:
          php-cs-fixer-version: v3.34.1

  build:
    needs: [php-cs-fixer]
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6
      with:
        working_dir: 'src'
        args: "--ignore-platform-reqs --optimize-autoloader"
        dev: no

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r vendor.zip src
