on:
  workflow_run:
    workflows: [ 'Build release' ]
    branches:
      - 'master'
    types:
      - completed
  push:
    tags:
      - '*.*.*'
jobs:
  release:
    name: Make release
    runs-on: ubuntu-latest
    #    if: ${{ github.ref_type == 'tag' }}
    steps:
      - run: |
          echo 123;

#      - name: Restore release
#        id: restore-release
#        uses: actions/cache@v3
#        with:
#          key: ${{ github.sha }}-release
#          path: ./release
#
#      - uses: softprops/action-gh-release@v1
#        name: Create release
#        with:
#          files: release/*.zip
#          draft: true
#          generate_release_notes: true