on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ github.ref_name }}

  test2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.ref_type }}

  release:
    name: Make release
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == tag }}
    needs: [ test, test2 ]
    steps:
      - run: |
          echo 123;
#      - name: Restore release
#        id: restore-release
#        uses: actions/cache@v3
#        with:
#          key: ${{ github.sha }}-release
#          path: ./release
#
#      - uses: softprops/action-gh-release@v1
#        name: Create release
#        with:
#          files: release/*.zip
#          draft: true
#          generate_release_notes: true